name: Prepare build environment
        
runs:
    using: composite
    steps:
        -   id: setup-python
            uses: actions/setup-python@v5
            with:
                python-version: '3.11'
                cache: 'pipenv'
        -   name: Setup base environment
            if: ${{ ! cancelled() }}
            shell: bash
            run: |
                echo "timestamp=$(date +%s)" >> $GITHUB_ENV
                echo "PIPENV_VERBOSITY=-1" >> $GITHUB_ENV
        -   name: Install pipenv
            if: ${{ ! cancelled() }}
            shell: bash
            run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
        -   name: Setup pipenv environment
            if: ${{ ! cancelled() }}
            shell: bash
            run: |
                pwd
                pipenv install
