name: Prepare build environment
        
runs:
    using: composite
    steps:
        -   id: setup-python
            uses: actions/setup-python@v5
            with:
                python-version: '3.11'
                cache: 'pipenv'
            shell: bash
        -   name: Setup base environment
            if: ${{ ! cancelled() }}
            run: |
                echo "timestamp=$(date +%s)" >> $GITHUB_ENV
                echo "PIPENV_VERBOSITY=-1" >> $GITHUB_ENV
        -   name: Setup cache for retool
            if: ${{ ! cancelled() }}
            id: retool-cache
            uses: actions/cache@v4
            with: 
                path: ./retool-config
                key: ${{ runner.os }}-retool-clonelists
            shell: bash
        -   name: Install pipenv
            if: ${{ ! cancelled() }}
            run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
            shell: bash
        -   name: Setup pipenv environment
            if: ${{ ! cancelled() }}
            run: |
                pwd
                pipenv install
            shell: bash
        -   name: Update retool clone lists
            if: ${{ ! cancelled() }} && steps.retool-cache.outputs.cache-hit != 'true'
            working-directory: ./retool-config
            run: |
                pwd
                pipenv run retool --update
            shell: bash