name: Daily rebuild

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:

env:
  tag: latest
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pipenv'

      - name: Setup base environment
        if: ${{ ! cancelled() }}
        run: |
          echo "timestamp=$(date +%s)" >> $GITHUB_ENV
          echo "PIPENV_VERBOSITY=-1" >> $GITHUB_ENV

      - name: Install pipenv
        if: ${{ ! cancelled() }}
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
        
      - name: Setup pipenv environment
        if: ${{ ! cancelled() }}
        run: |
          pwd
          pipenv install
        
      - name: Update retool clone lists
        if: ${{ ! cancelled() }}
        working-directory: ./retool-config
        run: |
          pwd
          pipenv run retool --update

      - name: Download dats and generate profile.xml for Redump
        if: ${{ ! cancelled() }}
        run: pipenv run python redump.py

      - name: Download dats and generate profile.xml for No-Intro
        if: ${{ ! cancelled() }}
        run: pipenv run python no_intro.py
        
      - name: Download dats and generate profile.xml for No-Intro (Parent-Clone)
        if: ${{ ! cancelled() }}
        run: pipenv run python no_intro_parent_clone.py
        
      - name: Download dats and generate profile.xml for Translated-En set from Archive.org
        if: ${{ ! cancelled() }}
        run: pipenv run python translated-en.py
        
      - name: Download dats and generate profile.xml for FinalBurn Neo
        if: ${{ ! cancelled() }}
        run: pipenv run python fbneo.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Download dats and generate profile.xml for FinalBurn Neo specialty
        if: ${{ ! cancelled() }}
        run: pipenv run python fbneo-specialty.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # HTGD disabled for now
      #- name: Download dats and generate profile.xml for HTGD
      #  if: ${{ ! cancelled() }}
      #  run: pipenv run python smdb.py
      
      # dats.site disabled for now
      #- name: Download dats and generate profile.xml for dats.site
      #  if: ${{ ! cancelled() }}
      #  run: pipenv run python dats-site.py

      - name: Create release
        if: ${{ ! cancelled() }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "*.xml,*.zip"
          commit: master
          name: Daily_Rebuild
          makeLatest: true
          tag: ${{ env.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "Automatically released by github actions"
