name: Daily rebuild

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:

env:
  tag: latest
  
jobs:
  fbneo:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/workflows/prepare-build-env
      - name: Download dats and generate profile.xml for FinalBurn Neo
        if: ${{ ! cancelled() }}
        run: pipenv run python src/fbneo.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download dats and generate profile.xml for FinalBurn Neo specialty
        if: ${{ ! cancelled() }}
        run: pipenv run python src/fbneo-specialty.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/workflows/update-release-files

  redump:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/workflows/prepare-build-env
      - name: Download dats and generate profile.xml for Redump
        if: ${{ ! cancelled() }}
        run: pipenv run python src/redump.py
      - uses: ./.github/workflows/update-release-files

  no-intro:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/workflows/prepare-build-env
      - name: Download dats and generate profile.xml for No-Intro
        if: ${{ ! cancelled() }}
        run: pipenv run python src/no_intro.py
      - name: Download dats and generate profile.xml for No-Intro (Parent-Clone)
        if: ${{ ! cancelled() }}
        run: pipenv run python src/no_intro_parent_clone.py
      - uses: ./.github/workflows/update-release-files
    
  translated-en:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/workflows/prepare-build-env
      - name: Download dats and generate profile.xml for Translated-En set from Archive.org
        if: ${{ ! cancelled() }}
        run: pipenv run python src/translated-en.py
      - uses: ./.github/workflows/update-release-files
      
  #HTGD disabled for now
  
  #htgd:
  # runs-on: ubuntu-latest
  # steps:
  #  - id: checkout-repo
  #     uses: actions/checkout@v4
  #     with:
  #       submodules: recursive
  #   - uses: ./.github/workflows/prepare-build-env
  #  - name: Download dats and generate profile.xml for HTGD
  #    if: ${{ ! cancelled() }}
  #    run: pipenv run python src/smdb.py
  #  - uses: ./.github/workflows/update-release-files
      
  #dats.site disabled for now

  #dats-site:
  # runs-on: ubuntu-latest
  # steps:
  #  - id: checkout-repo
  #     uses: actions/checkout@v4
  #     with:
  #       submodules: recursive
  #   - uses: ./.github/workflows/prepare-build-env
  #  - name: Download dats and generate profile.xml for dats.site
  #    if: ${{ ! cancelled() }}
  #    run: pipenv run python src/dats-site.py
  #  - uses: ./.github/workflows/update-release-files