name: Daily WWW clrmamepro profiles

on:
    push:
    schedule:
        - cron:  '0 12 * * *'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Install pipenv
          run: sudo pip install pipenv

        - name: Install dependencies using Pipenv
          run: pipenv install --deploy

        - name: Download dats and generate profile.xml
          id: generator_redump
          run: pipenv run python3 redump.py

        - name: Download dats and generate profile.xml
          id: generator_no_intro
          run: pipenv run python3 no-intro.py

        - name: Download dats and generate profile.xml
          id: generator_smdb
          run: pipenv run python3 smdb.py

        - name: Upload assets to release
          uses: meeDamian/github-release@2.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            tag: latest
            name: latest
            allow_override: true
            gzip: false
            files: >
                no-intro(standard).xml
                no-intro(standard).zip
                no-intro(parent-clone).xml
                no-intro(parent-clone).zip
                redump.xml
                redump.zip
                smdb.zip
                smdb.xml
